//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AtuneAPI.PersonWebServicePRO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserWebServiceSoap", Namespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/")]
    public partial class UserWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOrUpdateUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserWebService() {
            this.Url = global::AtuneAPI.Properties.Settings.Default.AtuneAPI_PersonWebServicePRO_UserWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUsersCompletedEventHandler GetUsersCompleted;
        
        /// <remarks/>
        public event GetUserCompletedEventHandler GetUserCompleted;
        
        /// <remarks/>
        public event SaveOrUpdateUserCompletedEventHandler SaveOrUpdateUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.a-tune.de/services/tickatlab/user/userwebservice/GetUsers", RequestNamespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/", ResponseNamespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceUser[] GetUsers(ServiceUserFilter filter) {
            object[] results = this.Invoke("GetUsers", new object[] {
                        filter});
            return ((ServiceUser[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersAsync(ServiceUserFilter filter) {
            this.GetUsersAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetUsersAsync(ServiceUserFilter filter, object userState) {
            if ((this.GetUsersOperationCompleted == null)) {
                this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
            }
            this.InvokeAsync("GetUsers", new object[] {
                        filter}, this.GetUsersOperationCompleted, userState);
        }
        
        private void OnGetUsersOperationCompleted(object arg) {
            if ((this.GetUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.a-tune.de/services/tickatlab/user/userwebservice/GetUser", RequestNamespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/", ResponseNamespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceUser GetUser(string login) {
            object[] results = this.Invoke("GetUser", new object[] {
                        login});
            return ((ServiceUser)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAsync(string login) {
            this.GetUserAsync(login, null);
        }
        
        /// <remarks/>
        public void GetUserAsync(string login, object userState) {
            if ((this.GetUserOperationCompleted == null)) {
                this.GetUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserOperationCompleted);
            }
            this.InvokeAsync("GetUser", new object[] {
                        login}, this.GetUserOperationCompleted, userState);
        }
        
        private void OnGetUserOperationCompleted(object arg) {
            if ((this.GetUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserCompleted(this, new GetUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.a-tune.de/services/tickatlab/user/userwebservice/SaveOrUpdateUser", RequestNamespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/", ResponseNamespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceUser SaveOrUpdateUser(ServiceUser user) {
            object[] results = this.Invoke("SaveOrUpdateUser", new object[] {
                        user});
            return ((ServiceUser)(results[0]));
        }
        
        /// <remarks/>
        public void SaveOrUpdateUserAsync(ServiceUser user) {
            this.SaveOrUpdateUserAsync(user, null);
        }
        
        /// <remarks/>
        public void SaveOrUpdateUserAsync(ServiceUser user, object userState) {
            if ((this.SaveOrUpdateUserOperationCompleted == null)) {
                this.SaveOrUpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOrUpdateUserOperationCompleted);
            }
            this.InvokeAsync("SaveOrUpdateUser", new object[] {
                        user}, this.SaveOrUpdateUserOperationCompleted, userState);
        }
        
        private void OnSaveOrUpdateUserOperationCompleted(object arg) {
            if ((this.SaveOrUpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveOrUpdateUserCompleted(this, new SaveOrUpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/")]
    public partial class ServiceUserFilter {
        
        private string loginField;
        
        private string externalId1Field;
        
        private string externalId2Field;
        
        private string externalId3Field;
        
        private string externalId4Field;
        
        private string externalId5Field;
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId1 {
            get {
                return this.externalId1Field;
            }
            set {
                this.externalId1Field = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId2 {
            get {
                return this.externalId2Field;
            }
            set {
                this.externalId2Field = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId3 {
            get {
                return this.externalId3Field;
            }
            set {
                this.externalId3Field = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId4 {
            get {
                return this.externalId4Field;
            }
            set {
                this.externalId4Field = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId5 {
            get {
                return this.externalId5Field;
            }
            set {
                this.externalId5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.a-tune.de/services/tickatlab/user/userwebservice/")]
    public partial class ServiceUser {
        
        private System.Nullable<bool> isLockedField;
        
        private string titleField;
        
        private string loginField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string departmentField;
        
        private string phoneNumberField;
        
        private string externalId1Field;
        
        private string externalId2Field;
        
        private string externalId3Field;
        
        private string externalId4Field;
        
        private string externalId5Field;
        
        private string teamField;
        
        private string[] additionalTeamsField;
        
        private string locationField;
        
        private string[] locationAccessAssignmentsField;
        
        private string[] rolesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId1 {
            get {
                return this.externalId1Field;
            }
            set {
                this.externalId1Field = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId2 {
            get {
                return this.externalId2Field;
            }
            set {
                this.externalId2Field = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId3 {
            get {
                return this.externalId3Field;
            }
            set {
                this.externalId3Field = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId4 {
            get {
                return this.externalId4Field;
            }
            set {
                this.externalId4Field = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId5 {
            get {
                return this.externalId5Field;
            }
            set {
                this.externalId5Field = value;
            }
        }
        
        /// <remarks/>
        public string Team {
            get {
                return this.teamField;
            }
            set {
                this.teamField = value;
            }
        }
        
        /// <remarks/>
        public string[] AdditionalTeams {
            get {
                return this.additionalTeamsField;
            }
            set {
                this.additionalTeamsField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string[] LocationAccessAssignments {
            get {
                return this.locationAccessAssignmentsField;
            }
            set {
                this.locationAccessAssignmentsField = value;
            }
        }
        
        /// <remarks/>
        public string[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceUser[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceUser[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUserCompletedEventHandler(object sender, GetUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveOrUpdateUserCompletedEventHandler(object sender, SaveOrUpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveOrUpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveOrUpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceUser)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591